module Text.Greek.Script.Unicode where 

import Text.Greek.Script

unicodeTokenPairs :: [(Char, Token)]
unicodeTokenPairs =
  [ ('\x0386', Token Alpha Uppercase (Just Acute) Nothing Nothing Nothing Nothing)
  , ('\x0388', Token Epsilon Uppercase (Just Acute) Nothing Nothing Nothing Nothing)
  , ('\x0389', Token Eta Uppercase (Just Acute) Nothing Nothing Nothing Nothing)
  , ('\x038A', Token Iota Uppercase (Just Acute) Nothing Nothing Nothing Nothing)
  , ('\x038C', Token Omicron Uppercase (Just Acute) Nothing Nothing Nothing Nothing)
  , ('\x038E', Token Upsilon Uppercase (Just Acute) Nothing Nothing Nothing Nothing)
  , ('\x038F', Token Omega Uppercase (Just Acute) Nothing Nothing Nothing Nothing)
  , ('\x0390', Token Iota Lowercase (Just Acute) Nothing Nothing (Just Diaeresis) Nothing)
  , ('\x0391', Token Alpha Uppercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x0392', Token Beta Uppercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x0393', Token Gamma Uppercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x0394', Token Delta Uppercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x0395', Token Epsilon Uppercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x0396', Token Zeta Uppercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x0397', Token Eta Uppercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x0398', Token Theta Uppercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x0399', Token Iota Uppercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x039A', Token Kappa Uppercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x039B', Token Lambda Uppercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x039C', Token Mu Uppercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x039D', Token Nu Uppercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x039E', Token Xi Uppercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x039F', Token Omicron Uppercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x03A0', Token Pi Uppercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x03A1', Token Rho Uppercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x03A3', Token Sigma Uppercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x03A4', Token Tau Uppercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x03A5', Token Upsilon Uppercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x03A6', Token Phi Uppercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x03A7', Token Chi Uppercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x03A8', Token Psi Uppercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x03A9', Token Omega Uppercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x03AA', Token Iota Uppercase Nothing Nothing Nothing (Just Diaeresis) Nothing)
  , ('\x03AB', Token Upsilon Uppercase Nothing Nothing Nothing (Just Diaeresis) Nothing)
  , ('\x03AC', Token Alpha Lowercase (Just Acute) Nothing Nothing Nothing Nothing)
  , ('\x03AD', Token Epsilon Lowercase (Just Acute) Nothing Nothing Nothing Nothing)
  , ('\x03AE', Token Eta Lowercase (Just Acute) Nothing Nothing Nothing Nothing)
  , ('\x03AF', Token Iota Lowercase (Just Acute) Nothing Nothing Nothing Nothing)
  , ('\x03B0', Token Upsilon Lowercase (Just Acute) Nothing Nothing (Just Diaeresis) Nothing)
  , ('\x03B1', Token Alpha Lowercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x03B2', Token Beta Lowercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x03B3', Token Gamma Lowercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x03B4', Token Delta Lowercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x03B5', Token Epsilon Lowercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x03B6', Token Zeta Lowercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x03B7', Token Eta Lowercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x03B8', Token Theta Lowercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x03B9', Token Iota Lowercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x03BA', Token Kappa Lowercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x03BB', Token Lambda Lowercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x03BC', Token Mu Lowercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x03BD', Token Nu Lowercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x03BE', Token Xi Lowercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x03BF', Token Omicron Lowercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x03C0', Token Pi Lowercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x03C1', Token Rho Lowercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x03C2', Token Sigma Lowercase Nothing Nothing Nothing Nothing (Just FinalForm))
  , ('\x03C3', Token Sigma Lowercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x03C4', Token Tau Lowercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x03C5', Token Upsilon Lowercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x03C6', Token Phi Lowercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x03C7', Token Chi Lowercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x03C8', Token Psi Lowercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x03C9', Token Omega Lowercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x03CA', Token Iota Lowercase Nothing Nothing Nothing (Just Diaeresis) Nothing)
  , ('\x03CB', Token Upsilon Lowercase Nothing Nothing Nothing (Just Diaeresis) Nothing)
  , ('\x03CC', Token Omicron Lowercase (Just Acute) Nothing Nothing Nothing Nothing)
  , ('\x03CD', Token Upsilon Lowercase (Just Acute) Nothing Nothing Nothing Nothing)
  , ('\x03CE', Token Omega Lowercase (Just Acute) Nothing Nothing Nothing Nothing)
  , ('\x1F00', Token Alpha Lowercase Nothing (Just Smooth) Nothing Nothing Nothing)
  , ('\x1F01', Token Alpha Lowercase Nothing (Just Rough) Nothing Nothing Nothing)
  , ('\x1F02', Token Alpha Lowercase (Just Grave) (Just Smooth) Nothing Nothing Nothing)
  , ('\x1F03', Token Alpha Lowercase (Just Grave) (Just Rough) Nothing Nothing Nothing)
  , ('\x1F04', Token Alpha Lowercase (Just Acute) (Just Smooth) Nothing Nothing Nothing)
  , ('\x1F05', Token Alpha Lowercase (Just Acute) (Just Rough) Nothing Nothing Nothing)
  , ('\x1F06', Token Alpha Lowercase (Just Circumflex) (Just Smooth) Nothing Nothing Nothing)
  , ('\x1F07', Token Alpha Lowercase (Just Circumflex) (Just Rough) Nothing Nothing Nothing)
  , ('\x1F08', Token Alpha Uppercase Nothing (Just Smooth) Nothing Nothing Nothing)
  , ('\x1F09', Token Alpha Uppercase Nothing (Just Rough) Nothing Nothing Nothing)
  , ('\x1F0A', Token Alpha Uppercase (Just Grave) (Just Smooth) Nothing Nothing Nothing)
  , ('\x1F0B', Token Alpha Uppercase (Just Grave) (Just Rough) Nothing Nothing Nothing)
  , ('\x1F0C', Token Alpha Uppercase (Just Acute) (Just Smooth) Nothing Nothing Nothing)
  , ('\x1F0D', Token Alpha Uppercase (Just Acute) (Just Rough) Nothing Nothing Nothing)
  , ('\x1F0E', Token Alpha Uppercase (Just Circumflex) (Just Smooth) Nothing Nothing Nothing)
  , ('\x1F0F', Token Alpha Uppercase (Just Circumflex) (Just Rough) Nothing Nothing Nothing)
  , ('\x1F10', Token Epsilon Lowercase Nothing (Just Smooth) Nothing Nothing Nothing)
  , ('\x1F11', Token Epsilon Lowercase Nothing (Just Rough) Nothing Nothing Nothing)
  , ('\x1F12', Token Epsilon Lowercase (Just Grave) (Just Smooth) Nothing Nothing Nothing)
  , ('\x1F13', Token Epsilon Lowercase (Just Grave) (Just Rough) Nothing Nothing Nothing)
  , ('\x1F14', Token Epsilon Lowercase (Just Acute) (Just Smooth) Nothing Nothing Nothing)
  , ('\x1F15', Token Epsilon Lowercase (Just Acute) (Just Rough) Nothing Nothing Nothing)
  , ('\x1F18', Token Epsilon Uppercase Nothing (Just Smooth) Nothing Nothing Nothing)
  , ('\x1F19', Token Epsilon Uppercase Nothing (Just Rough) Nothing Nothing Nothing)
  , ('\x1F1A', Token Epsilon Uppercase (Just Grave) (Just Smooth) Nothing Nothing Nothing)
  , ('\x1F1B', Token Epsilon Uppercase (Just Grave) (Just Rough) Nothing Nothing Nothing)
  , ('\x1F1C', Token Epsilon Uppercase (Just Acute) (Just Smooth) Nothing Nothing Nothing)
  , ('\x1F1D', Token Epsilon Uppercase (Just Acute) (Just Rough) Nothing Nothing Nothing)
  , ('\x1F20', Token Eta Lowercase Nothing (Just Smooth) Nothing Nothing Nothing)
  , ('\x1F21', Token Eta Lowercase Nothing (Just Rough) Nothing Nothing Nothing)
  , ('\x1F22', Token Eta Lowercase (Just Grave) (Just Smooth) Nothing Nothing Nothing)
  , ('\x1F23', Token Eta Lowercase (Just Grave) (Just Rough) Nothing Nothing Nothing)
  , ('\x1F24', Token Eta Lowercase (Just Acute) (Just Smooth) Nothing Nothing Nothing)
  , ('\x1F25', Token Eta Lowercase (Just Acute) (Just Rough) Nothing Nothing Nothing)
  , ('\x1F26', Token Eta Lowercase (Just Circumflex) (Just Smooth) Nothing Nothing Nothing)
  , ('\x1F27', Token Eta Lowercase (Just Circumflex) (Just Rough) Nothing Nothing Nothing)
  , ('\x1F28', Token Eta Uppercase Nothing (Just Smooth) Nothing Nothing Nothing)
  , ('\x1F29', Token Eta Uppercase Nothing (Just Rough) Nothing Nothing Nothing)
  , ('\x1F2A', Token Eta Uppercase (Just Grave) (Just Smooth) Nothing Nothing Nothing)
  , ('\x1F2B', Token Eta Uppercase (Just Grave) (Just Rough) Nothing Nothing Nothing)
  , ('\x1F2C', Token Eta Uppercase (Just Acute) (Just Smooth) Nothing Nothing Nothing)
  , ('\x1F2D', Token Eta Uppercase (Just Acute) (Just Rough) Nothing Nothing Nothing)
  , ('\x1F2E', Token Eta Uppercase (Just Circumflex) (Just Smooth) Nothing Nothing Nothing)
  , ('\x1F2F', Token Eta Uppercase (Just Circumflex) (Just Rough) Nothing Nothing Nothing)
  , ('\x1F30', Token Iota Lowercase Nothing (Just Smooth) Nothing Nothing Nothing)
  , ('\x1F31', Token Iota Lowercase Nothing (Just Rough) Nothing Nothing Nothing)
  , ('\x1F32', Token Iota Lowercase (Just Grave) (Just Smooth) Nothing Nothing Nothing)
  , ('\x1F33', Token Iota Lowercase (Just Grave) (Just Rough) Nothing Nothing Nothing)
  , ('\x1F34', Token Iota Lowercase (Just Acute) (Just Smooth) Nothing Nothing Nothing)
  , ('\x1F35', Token Iota Lowercase (Just Acute) (Just Rough) Nothing Nothing Nothing)
  , ('\x1F36', Token Iota Lowercase (Just Circumflex) (Just Smooth) Nothing Nothing Nothing)
  , ('\x1F37', Token Iota Lowercase (Just Circumflex) (Just Rough) Nothing Nothing Nothing)
  , ('\x1F38', Token Iota Uppercase Nothing (Just Smooth) Nothing Nothing Nothing)
  , ('\x1F39', Token Iota Uppercase Nothing (Just Rough) Nothing Nothing Nothing)
  , ('\x1F3A', Token Iota Uppercase (Just Grave) (Just Smooth) Nothing Nothing Nothing)
  , ('\x1F3B', Token Iota Uppercase (Just Grave) (Just Rough) Nothing Nothing Nothing)
  , ('\x1F3C', Token Iota Uppercase (Just Acute) (Just Smooth) Nothing Nothing Nothing)
  , ('\x1F3D', Token Iota Uppercase (Just Acute) (Just Rough) Nothing Nothing Nothing)
  , ('\x1F3E', Token Iota Uppercase (Just Circumflex) (Just Smooth) Nothing Nothing Nothing)
  , ('\x1F3F', Token Iota Uppercase (Just Circumflex) (Just Rough) Nothing Nothing Nothing)
  , ('\x1F40', Token Omicron Lowercase Nothing (Just Smooth) Nothing Nothing Nothing)
  , ('\x1F41', Token Omicron Lowercase Nothing (Just Rough) Nothing Nothing Nothing)
  , ('\x1F42', Token Omicron Lowercase (Just Grave) (Just Smooth) Nothing Nothing Nothing)
  , ('\x1F43', Token Omicron Lowercase (Just Grave) (Just Rough) Nothing Nothing Nothing)
  , ('\x1F44', Token Omicron Lowercase (Just Acute) (Just Smooth) Nothing Nothing Nothing)
  , ('\x1F45', Token Omicron Lowercase (Just Acute) (Just Rough) Nothing Nothing Nothing)
  , ('\x1F48', Token Omicron Uppercase Nothing (Just Smooth) Nothing Nothing Nothing)
  , ('\x1F49', Token Omicron Uppercase Nothing (Just Rough) Nothing Nothing Nothing)
  , ('\x1F4A', Token Omicron Uppercase (Just Grave) (Just Smooth) Nothing Nothing Nothing)
  , ('\x1F4B', Token Omicron Uppercase (Just Grave) (Just Rough) Nothing Nothing Nothing)
  , ('\x1F4C', Token Omicron Uppercase (Just Acute) (Just Smooth) Nothing Nothing Nothing)
  , ('\x1F4D', Token Omicron Uppercase (Just Acute) (Just Rough) Nothing Nothing Nothing)
  , ('\x1F50', Token Upsilon Lowercase Nothing (Just Smooth) Nothing Nothing Nothing)
  , ('\x1F51', Token Upsilon Lowercase Nothing (Just Rough) Nothing Nothing Nothing)
  , ('\x1F52', Token Upsilon Lowercase (Just Grave) (Just Smooth) Nothing Nothing Nothing)
  , ('\x1F53', Token Upsilon Lowercase (Just Grave) (Just Rough) Nothing Nothing Nothing)
  , ('\x1F54', Token Upsilon Lowercase (Just Acute) (Just Smooth) Nothing Nothing Nothing)
  , ('\x1F55', Token Upsilon Lowercase (Just Acute) (Just Rough) Nothing Nothing Nothing)
  , ('\x1F56', Token Upsilon Lowercase (Just Circumflex) (Just Smooth) Nothing Nothing Nothing)
  , ('\x1F57', Token Upsilon Lowercase (Just Circumflex) (Just Rough) Nothing Nothing Nothing)
  , ('\x1F59', Token Upsilon Uppercase Nothing (Just Rough) Nothing Nothing Nothing)
  , ('\x1F5B', Token Upsilon Uppercase (Just Grave) (Just Rough) Nothing Nothing Nothing)
  , ('\x1F5D', Token Upsilon Uppercase (Just Acute) (Just Rough) Nothing Nothing Nothing)
  , ('\x1F5F', Token Upsilon Uppercase (Just Circumflex) (Just Rough) Nothing Nothing Nothing)
  , ('\x1F60', Token Omega Lowercase Nothing (Just Smooth) Nothing Nothing Nothing)
  , ('\x1F61', Token Omega Lowercase Nothing (Just Rough) Nothing Nothing Nothing)
  , ('\x1F62', Token Omega Lowercase (Just Grave) (Just Smooth) Nothing Nothing Nothing)
  , ('\x1F63', Token Omega Lowercase (Just Grave) (Just Rough) Nothing Nothing Nothing)
  , ('\x1F64', Token Omega Lowercase (Just Acute) (Just Smooth) Nothing Nothing Nothing)
  , ('\x1F65', Token Omega Lowercase (Just Acute) (Just Rough) Nothing Nothing Nothing)
  , ('\x1F66', Token Omega Lowercase (Just Circumflex) (Just Smooth) Nothing Nothing Nothing)
  , ('\x1F67', Token Omega Lowercase (Just Circumflex) (Just Rough) Nothing Nothing Nothing)
  , ('\x1F68', Token Omega Uppercase Nothing (Just Smooth) Nothing Nothing Nothing)
  , ('\x1F69', Token Omega Uppercase Nothing (Just Rough) Nothing Nothing Nothing)
  , ('\x1F6A', Token Omega Uppercase (Just Grave) (Just Smooth) Nothing Nothing Nothing)
  , ('\x1F6B', Token Omega Uppercase (Just Grave) (Just Rough) Nothing Nothing Nothing)
  , ('\x1F6C', Token Omega Uppercase (Just Acute) (Just Smooth) Nothing Nothing Nothing)
  , ('\x1F6D', Token Omega Uppercase (Just Acute) (Just Rough) Nothing Nothing Nothing)
  , ('\x1F6E', Token Omega Uppercase (Just Circumflex) (Just Smooth) Nothing Nothing Nothing)
  , ('\x1F6F', Token Omega Uppercase (Just Circumflex) (Just Rough) Nothing Nothing Nothing)
  , ('\x1F70', Token Alpha Lowercase (Just Grave) Nothing Nothing Nothing Nothing)
  , ('\x1F71', Token Alpha Lowercase (Just Acute) Nothing Nothing Nothing Nothing)
  , ('\x1F72', Token Epsilon Lowercase (Just Grave) Nothing Nothing Nothing Nothing)
  , ('\x1F73', Token Epsilon Lowercase (Just Acute) Nothing Nothing Nothing Nothing)
  , ('\x1F74', Token Eta Lowercase (Just Grave) Nothing Nothing Nothing Nothing)
  , ('\x1F75', Token Eta Lowercase (Just Acute) Nothing Nothing Nothing Nothing)
  , ('\x1F76', Token Iota Lowercase (Just Grave) Nothing Nothing Nothing Nothing)
  , ('\x1F77', Token Iota Lowercase (Just Acute) Nothing Nothing Nothing Nothing)
  , ('\x1F78', Token Omicron Lowercase (Just Grave) Nothing Nothing Nothing Nothing)
  , ('\x1F79', Token Omicron Lowercase (Just Acute) Nothing Nothing Nothing Nothing)
  , ('\x1F7A', Token Upsilon Lowercase (Just Grave) Nothing Nothing Nothing Nothing)
  , ('\x1F7B', Token Upsilon Lowercase (Just Acute) Nothing Nothing Nothing Nothing)
  , ('\x1F7C', Token Omega Lowercase (Just Grave) Nothing Nothing Nothing Nothing)
  , ('\x1F7D', Token Omega Lowercase (Just Acute) Nothing Nothing Nothing Nothing)
  , ('\x1F80', Token Alpha Lowercase Nothing (Just Smooth) (Just IotaSubscript) Nothing Nothing)
  , ('\x1F81', Token Alpha Lowercase Nothing (Just Rough) (Just IotaSubscript) Nothing Nothing)
  , ('\x1F82', Token Alpha Lowercase (Just Grave) (Just Smooth) (Just IotaSubscript) Nothing Nothing)
  , ('\x1F83', Token Alpha Lowercase (Just Grave) (Just Rough) (Just IotaSubscript) Nothing Nothing)
  , ('\x1F84', Token Alpha Lowercase (Just Acute) (Just Smooth) (Just IotaSubscript) Nothing Nothing)
  , ('\x1F85', Token Alpha Lowercase (Just Acute) (Just Rough) (Just IotaSubscript) Nothing Nothing)
  , ('\x1F86', Token Alpha Lowercase (Just Circumflex) (Just Smooth) (Just IotaSubscript) Nothing Nothing)
  , ('\x1F87', Token Alpha Lowercase (Just Circumflex) (Just Rough) (Just IotaSubscript) Nothing Nothing)
  , ('\x1F88', Token Alpha Uppercase Nothing (Just Smooth) (Just IotaSubscript) Nothing Nothing)
  , ('\x1F89', Token Alpha Uppercase Nothing (Just Rough) (Just IotaSubscript) Nothing Nothing)
  , ('\x1F8A', Token Alpha Uppercase (Just Grave) (Just Smooth) (Just IotaSubscript) Nothing Nothing)
  , ('\x1F8B', Token Alpha Uppercase (Just Grave) (Just Rough) (Just IotaSubscript) Nothing Nothing)
  , ('\x1F8C', Token Alpha Uppercase (Just Acute) (Just Smooth) (Just IotaSubscript) Nothing Nothing)
  , ('\x1F8D', Token Alpha Uppercase (Just Acute) (Just Rough) (Just IotaSubscript) Nothing Nothing)
  , ('\x1F8E', Token Alpha Uppercase (Just Circumflex) (Just Smooth) (Just IotaSubscript) Nothing Nothing)
  , ('\x1F8F', Token Alpha Uppercase (Just Circumflex) (Just Rough) (Just IotaSubscript) Nothing Nothing)
  , ('\x1F90', Token Eta Lowercase Nothing (Just Smooth) (Just IotaSubscript) Nothing Nothing)
  , ('\x1F91', Token Eta Lowercase Nothing (Just Rough) (Just IotaSubscript) Nothing Nothing)
  , ('\x1F92', Token Eta Lowercase (Just Grave) (Just Smooth) (Just IotaSubscript) Nothing Nothing)
  , ('\x1F93', Token Eta Lowercase (Just Grave) (Just Rough) (Just IotaSubscript) Nothing Nothing)
  , ('\x1F94', Token Eta Lowercase (Just Acute) (Just Smooth) (Just IotaSubscript) Nothing Nothing)
  , ('\x1F95', Token Eta Lowercase (Just Acute) (Just Rough) (Just IotaSubscript) Nothing Nothing)
  , ('\x1F96', Token Eta Lowercase (Just Circumflex) (Just Smooth) (Just IotaSubscript) Nothing Nothing)
  , ('\x1F97', Token Eta Lowercase (Just Circumflex) (Just Rough) (Just IotaSubscript) Nothing Nothing)
  , ('\x1F98', Token Eta Uppercase Nothing (Just Smooth) (Just IotaSubscript) Nothing Nothing)
  , ('\x1F99', Token Eta Uppercase Nothing (Just Rough) (Just IotaSubscript) Nothing Nothing)
  , ('\x1F9A', Token Eta Uppercase (Just Grave) (Just Smooth) (Just IotaSubscript) Nothing Nothing)
  , ('\x1F9B', Token Eta Uppercase (Just Grave) (Just Rough) (Just IotaSubscript) Nothing Nothing)
  , ('\x1F9C', Token Eta Uppercase (Just Acute) (Just Smooth) (Just IotaSubscript) Nothing Nothing)
  , ('\x1F9D', Token Eta Uppercase (Just Acute) (Just Rough) (Just IotaSubscript) Nothing Nothing)
  , ('\x1F9E', Token Eta Uppercase (Just Circumflex) (Just Smooth) (Just IotaSubscript) Nothing Nothing)
  , ('\x1F9F', Token Eta Uppercase (Just Circumflex) (Just Rough) (Just IotaSubscript) Nothing Nothing)
  , ('\x1FA0', Token Omega Lowercase Nothing (Just Smooth) (Just IotaSubscript) Nothing Nothing)
  , ('\x1FA1', Token Omega Lowercase Nothing (Just Rough) (Just IotaSubscript) Nothing Nothing)
  , ('\x1FA2', Token Omega Lowercase (Just Grave) (Just Smooth) (Just IotaSubscript) Nothing Nothing)
  , ('\x1FA3', Token Omega Lowercase (Just Grave) (Just Rough) (Just IotaSubscript) Nothing Nothing)
  , ('\x1FA4', Token Omega Lowercase (Just Acute) (Just Smooth) (Just IotaSubscript) Nothing Nothing)
  , ('\x1FA5', Token Omega Lowercase (Just Acute) (Just Rough) (Just IotaSubscript) Nothing Nothing)
  , ('\x1FA6', Token Omega Lowercase (Just Circumflex) (Just Smooth) (Just IotaSubscript) Nothing Nothing)
  , ('\x1FA7', Token Omega Lowercase (Just Circumflex) (Just Rough) (Just IotaSubscript) Nothing Nothing)
  , ('\x1FA8', Token Omega Uppercase Nothing (Just Smooth) (Just IotaSubscript) Nothing Nothing)
  , ('\x1FA9', Token Omega Uppercase Nothing (Just Rough) (Just IotaSubscript) Nothing Nothing)
  , ('\x1FAA', Token Omega Uppercase (Just Grave) (Just Smooth) (Just IotaSubscript) Nothing Nothing)
  , ('\x1FAB', Token Omega Uppercase (Just Grave) (Just Rough) (Just IotaSubscript) Nothing Nothing)
  , ('\x1FAC', Token Omega Uppercase (Just Acute) (Just Smooth) (Just IotaSubscript) Nothing Nothing)
  , ('\x1FAD', Token Omega Uppercase (Just Acute) (Just Rough) (Just IotaSubscript) Nothing Nothing)
  , ('\x1FAE', Token Omega Uppercase (Just Circumflex) (Just Smooth) (Just IotaSubscript) Nothing Nothing)
  , ('\x1FAF', Token Omega Uppercase (Just Circumflex) (Just Rough) (Just IotaSubscript) Nothing Nothing)
  , ('\x1FB0', Token Alpha Lowercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x1FB1', Token Alpha Lowercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x1FB2', Token Alpha Lowercase (Just Grave) Nothing (Just IotaSubscript) Nothing Nothing)
  , ('\x1FB3', Token Alpha Lowercase Nothing Nothing (Just IotaSubscript) Nothing Nothing)
  , ('\x1FB4', Token Alpha Lowercase (Just Acute) Nothing (Just IotaSubscript) Nothing Nothing)
  , ('\x1FB6', Token Alpha Lowercase (Just Circumflex) Nothing Nothing Nothing Nothing)
  , ('\x1FB7', Token Alpha Lowercase (Just Circumflex) Nothing (Just IotaSubscript) Nothing Nothing)
  , ('\x1FB8', Token Alpha Uppercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x1FB9', Token Alpha Uppercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x1FBA', Token Alpha Uppercase (Just Grave) Nothing Nothing Nothing Nothing)
  , ('\x1FBB', Token Alpha Uppercase (Just Acute) Nothing Nothing Nothing Nothing)
  , ('\x1FBC', Token Alpha Uppercase Nothing Nothing (Just IotaSubscript) Nothing Nothing)
  , ('\x1FC2', Token Eta Lowercase (Just Grave) Nothing (Just IotaSubscript) Nothing Nothing)
  , ('\x1FC3', Token Eta Lowercase Nothing Nothing (Just IotaSubscript) Nothing Nothing)
  , ('\x1FC4', Token Eta Lowercase (Just Acute) Nothing (Just IotaSubscript) Nothing Nothing)
  , ('\x1FC6', Token Eta Lowercase (Just Circumflex) Nothing Nothing Nothing Nothing)
  , ('\x1FC7', Token Eta Lowercase (Just Circumflex) Nothing (Just IotaSubscript) Nothing Nothing)
  , ('\x1FC8', Token Epsilon Uppercase (Just Grave) Nothing Nothing Nothing Nothing)
  , ('\x1FC9', Token Epsilon Uppercase (Just Acute) Nothing Nothing Nothing Nothing)
  , ('\x1FCA', Token Eta Uppercase (Just Grave) Nothing Nothing Nothing Nothing)
  , ('\x1FCB', Token Eta Uppercase (Just Acute) Nothing Nothing Nothing Nothing)
  , ('\x1FCC', Token Eta Uppercase Nothing Nothing (Just IotaSubscript) Nothing Nothing)
  , ('\x1FD0', Token Iota Lowercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x1FD1', Token Iota Lowercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x1FD2', Token Iota Lowercase (Just Grave) Nothing Nothing (Just Diaeresis) Nothing)
  , ('\x1FD3', Token Iota Lowercase (Just Acute) Nothing Nothing (Just Diaeresis) Nothing)
  , ('\x1FD6', Token Iota Lowercase (Just Circumflex) Nothing Nothing Nothing Nothing)
  , ('\x1FD7', Token Iota Lowercase (Just Circumflex) Nothing Nothing (Just Diaeresis) Nothing)
  , ('\x1FD8', Token Iota Uppercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x1FD9', Token Iota Uppercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x1FDA', Token Iota Uppercase (Just Grave) Nothing Nothing Nothing Nothing)
  , ('\x1FDB', Token Iota Uppercase (Just Acute) Nothing Nothing Nothing Nothing)
  , ('\x1FE0', Token Upsilon Lowercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x1FE1', Token Upsilon Lowercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x1FE2', Token Upsilon Lowercase (Just Grave) Nothing Nothing (Just Diaeresis) Nothing)
  , ('\x1FE3', Token Upsilon Lowercase (Just Acute) Nothing Nothing (Just Diaeresis) Nothing)
  , ('\x1FE4', Token Rho Lowercase Nothing (Just Smooth) Nothing Nothing Nothing)
  , ('\x1FE5', Token Rho Lowercase Nothing (Just Rough) Nothing Nothing Nothing)
  , ('\x1FE6', Token Upsilon Lowercase (Just Circumflex) Nothing Nothing Nothing Nothing)
  , ('\x1FE7', Token Upsilon Lowercase (Just Circumflex) Nothing Nothing (Just Diaeresis) Nothing)
  , ('\x1FE8', Token Upsilon Uppercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x1FE9', Token Upsilon Uppercase Nothing Nothing Nothing Nothing Nothing)
  , ('\x1FEA', Token Upsilon Uppercase (Just Grave) Nothing Nothing Nothing Nothing)
  , ('\x1FEB', Token Upsilon Uppercase (Just Acute) Nothing Nothing Nothing Nothing)
  , ('\x1FEC', Token Rho Uppercase Nothing (Just Rough) Nothing Nothing Nothing)
  , ('\x1FF2', Token Omega Lowercase (Just Grave) Nothing (Just IotaSubscript) Nothing Nothing)
  , ('\x1FF3', Token Omega Lowercase Nothing Nothing (Just IotaSubscript) Nothing Nothing)
  , ('\x1FF4', Token Omega Lowercase (Just Acute) Nothing (Just IotaSubscript) Nothing Nothing)
  , ('\x1FF6', Token Omega Lowercase (Just Circumflex) Nothing Nothing Nothing Nothing)
  , ('\x1FF7', Token Omega Lowercase (Just Circumflex) Nothing (Just IotaSubscript) Nothing Nothing)
  , ('\x1FF8', Token Omicron Uppercase (Just Grave) Nothing Nothing Nothing Nothing)
  , ('\x1FF9', Token Omicron Uppercase (Just Acute) Nothing Nothing Nothing Nothing)
  , ('\x1FFA', Token Omega Uppercase (Just Grave) Nothing Nothing Nothing Nothing)
  , ('\x1FFB', Token Omega Uppercase (Just Acute) Nothing Nothing Nothing Nothing)
  , ('\x1FFC', Token Omega Uppercase Nothing Nothing (Just IotaSubscript) Nothing Nothing)
  ]
